# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='主题')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
    ]
